// Generated by CoffeeScript 1.8.0
var n, output, sid;

output = {};

sid = 'TPME.XAGUSD';

n = 0;

window.Resource.gameSeries.forEach(function(_arg, i) {
  var limit, tradedate;
  limit = _arg.limit, tradedate = _arg.tradedate;
  return $.getJSON("http://api.baidao.com/api/hq/mkdata.do?sid=" + sid + "&quotationType=60&limit=" + limit + "&tradedate=" + tradedate, (function(_this) {
    return function(data) {
      output["" + tradedate + "," + limit] = data;
      return console.log("已经加载到第" + (++n));
    };
  })(this));
});

setTimeout(function() {
  return console.log(JSON.stringify(output));
}, 10 * 1000);
