#Generated by CoffeeScript 1.7.1
fadeOut = (id, timeout) ->
  currentObject = $("." + id)
  maxHeight = parseInt currentObject.height 
  i = 0
  timer = setInterval(-> 
  	i++
  	value = parseFloat(i) * 0.01
  	currentObject.css({
  		'filter': 'alpha(opacity =' + i + ')' 
  		'-moz-opacity': value
  		'opacity': value
  		'height': maxHeight
  	})
  
	  if i == 100
	  	clearInterval timer
  , timeout)

fadeIn = (id, timeout) ->
  currentObject = $("." + id)
  maxHeight = parseInt currentObject.height
  i = 100
  currentTimer = setInterval(-> 
  	value = parseFloat(i) * 0.01
  	currentObject.css({
  		'filter': 'alpha(opacity =' + i + ')' 
  		'-moz-opacity': value
  		'opacity': value
  		'height': maxHeight
  	})
  	
  	i--
  
	  if i == 500
	  	clearInterval currentTimer  
  , timeout)

$('.js-play-game').click(->
  $(this).closest('div.js-paly-intro').css('display', 'none')
  $('div.js-taiji-sec').css('display', 'block')
)

option = {
  chart: 
    backgroundColor: 'black'
    renderTo: 'container'
  ,
  title: 
    text: 'Monthly Average Temperature'
    x: -20 #center
  ,
  subtitle: 
    text: 'Source: WorldClimate.com'
    x: -20
  ,
  colors: ['#0ff01a', '#38b843', '#ef3312', '#a04433']
  xAxis: 
    gridLineColor: '#197f07'
    gridLineWidth: 0
  ,
  yAxis: 
    title: 
      text: 'Temperature (°C)'
    ,
    plotLines: [{
      value: 0,
      width: 1,
      color: '#808080'
    }],
    gridLineColor: '#197f07',
    gridLineWidth: 0
  ,
  tooltip: 
    useHTML: true
    shared: true
    borderWidth: 0
    borderRadius: '10px'
    formatter: -> 
      "<div style='position: absolute; top:7px; border-color: transparent green transparent transparent; border-style: dashed dashed solid dashed;
      border-width: 8px'>" + "<div style='position: absolute; border-color: transparent green transparent transparent; border-style: dashed dashed solid dashed; border-width:8px; top: -8px; left: -6px;'></div>" + "<div></div></div><div style='position: relative; left: 16px; background: #084c1c; border: 2px solid green; border-radius: 10px; padding: 8px; font-size: 16px; display: block'>" + "<span style='color: white; display: block;'>行情进入了绿色" + "<br/>" + "区域，太极线发出" + "<br/>" + "下跌信号，请点击</span>" + "<span style='color: #00f901; display: block'>\"卖出平仓\"</span></div>" 
  ,
  legend: 
    layout: 'vertical'
    align: 'right'
    verticalAlign: 'middle'
    borderWidth: 0
  ,
  series: [{
    name: 'Tokyo',
    data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
  }, {
    name: 'New York',
    data: [0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
  }, {
    name: 'Berlin',
    data: [0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]
  }, {
    name: 'London',
    data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
  }]
}

$('.js-no-tip').click(->
  $(this).closest('div.js-taiji-sec').css('display', 'none')
  $('div.js-loading-timer').css('display', 'block')
  $('body').addClass('bodyColor')
  j = 3
  yui = setInterval (->
    if j == 0 
      $('.count-downgo').css('display', 'block')
    if j == -1
      $('div.js-loading-timer').css('display', 'none')
      $('div.js-taiji-line').css('display', 'block')
      $('body').removeClass('bodyColor')
      clearInterval(yui)
      taijiChart = new Highcharts.Chart(option)
    else 
      $('.count-down' + (j+1)).css('display', 'none')
      $('.count-down' + j).css('display', 'block')
    j--
    return
  ), 1000
)

$ ->
  # 根据设备的宽度自适应
  bodyWidth = parseFloat($('html').width())
  currentDevWidth = bodyWidth * 100 / 320
  $('html').css('font-size', currentDevWidth)

  setTimeout (->
    fadeIn('index-bodybg', 10)
    $('.index-bodybg').css('display', 'none')
    $('div.js-paly-intro').css('display', 'block')
    return
  ), 1000
  return
        


	

