#Generated by CoffeeScript 1.7.1
fadeOut : (id, timeout) ->
  currentObject = $("." + id)
  maxHeight = parseInt currentObject.height 
  i = 0
  timer = setInterval(-> 
  	i++
  	value = parseFloat(i) * 0.01
  	currentObject.css({
  		'filter': 'alpha(opacity =' + i + ')' 
  		'-moz-opacity': value
  		'opacity': value
  		'height': maxHeight
  	})
  
	  if i == 100
	  	clearInterval timer
  , timeout)

fadeIn: (id, timeout) ->
  currentObject = $("." + id)
  maxHeight = parseInt currentObject.height
  i = 100
  currentTimer = setInterval(-> 
  	value = parseFloat(i) * 0.01
  	currentObject.css({
  		'filter': 'alpha(opacity =' + i + ')' 
  		'-moz-opacity': value
  		'opacity': value
  		'height': maxHeight
  	})
  	
  	i--
  
	  if i == 500
	  	clearInterval curr        åΩΩΩentTimer  
  , timeout)

$ ->
  setTimeout (->
    #$(".index-bodybg").fadeOut 'slow'
    fadeOut 'index-bodybg', 2000
    $(".wrap").fadeIn 'slow'
    return
  ), 1000
  return


	

