//Generated by CoffeeScript 1.7.1
var fadeOut = function(id, timeout) {
  var currentObject, currentTimer, i, maxHeight;
  currentObject = $("." + id);
  maxHeight = parseInt(currentObject.height);
  var i = 0;
  timer = setInterval(function() {
  	i ++;
  	var value = parseFloat(i) * 0.01;
  	currentObject.css({'filter': 'alpha(opacity =' + i + ')', '-moz-opacity': value, 'opacity': value, 'height': maxHeight});
  
	  if (i == 100) {
	  	clearInterval(timer);
	  }
  }, timeout);
};

var fadeIn = function(id, timeout) {
	var currentObject, currentTimer, i, maxHeight;
  currentObject = $("." + id);
  maxHeight = parseInt(currentObject.height);
  var i = 100;
  currentTimer = setInterval(function() {
 
  	var value = parseFloat(i) * 0.01;
  	currentObject.css({'filter': 'alpha(opacity =' + i + ')', '-moz-opacity': value, 'opacity': value, 'height': maxHeight});
  	i --;
  
	  if (i == 500) {
	  	clearInterval(currentTimer);
	  }
  }, timeout);
}

$(function() {
	var start = setTimeout(function() {
	  clearTimeout(start);
	}, 1000);

	fadeIn('index-bodybg', 10);
	$('.index-bodybg').css('display', 'none');
	fadeOut('wrap', 10);
});

